### ISSUE TITLE
Potential way for study group to learn more about Data Science

### ISSUE THREAD

**Issue by tonygardella** [bulib/studyGroup#12]
I came across these data science competitions and I remember that a lot of people were generally interested in data science: https://www.kaggle.com/competitions

Once we get started/improve perhaps we can make teams for these competitions. Let me know what you guys think!

**Comment by ashiklom** [comment]
+1

This seems like a fantastic way to learn both coding and statistics, AND a great way to bring together people from different disciplines behind a single project (or multiple projects!).

**Comment by adrianyi** [comment]
I would love to participate in these competitions! Definitely interested in data science.

**Comment by tomhohenstein** [comment]
+1 great idea! it could be a nice way to focus efforts or highlight certain packages or skills

**Comment by tmfarrell** [comment]
+1 

Given the limited course offerings in machine learning, it'd be cool to see a study group dedicated to this. I'd definitely attend.

**Comment by legolagon** [comment]
sounds good!

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Any interest in converting this into a [coworking session](http://mozillascience.github.io/studyGroupHandbook/event-types.html)? 

Best, 

Tom

**Comment by legolagon** [comment]
Yes, I'd be in for this too

**Comment by tomhohenstein** [comment]
How does sometime next week sound? 

I started a when2meet at: 
http://www.when2meet.com/?3720466-QzYBd

**Comment by tomhohenstein** [comment]
It looks like Thursday afternoon is best. How does from 5:00-7:00 sound? These sessions are more informal and people can come and go as their schedule dictates. 

Can we get STO 442 from 5-7 on Nov 5?

**Comment by ashiklom** [comment]
I personally won't be there because I'll be leaving town Thursday afternoon, but you can email our administrative assistant Frederick George (fgeorge@bu.edu) to see if you can reserve the room for that time.

**Comment by tomhohenstein** [comment]
@ashiklom  sorry we will miss you again! and thank you for the contact.

**Comment by tomhohenstein** [comment]
Hi Everyone, 

We have STO 442 from 5-7 on Thursday. Hope to see you there! 

-Tom

**Comment by tomhohenstein** [comment]
We had a small but good session - 4 attendees. We are going to do another session on Nov. 9. I'm going to close this issue and create a new issue called "Kaggle Competition"
