### ISSUE TITLE
Installing and using Jupyter 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#14]
Hi Everyone, 

How many of you are using [Jupyter](https://jupyter.org/) for documenting and sharing your work? If you're interested, I'd be happy to do a session on installing and using Jupyter - [including posting your work to GitHub](https://github.com/blog/1995-github-jupyter-notebooks-3). We could schedule the session for next week. 

Best, 

Tom

**Comment by ashiklom** [comment]
I've never used it or even heard of it, but I would be very interested in learning!

**Comment by ceholden** [comment]
I use Jupyter, the language inclusive renaming of the IPython notebook project, at least once a week for research or documenting projects and have used it extensively for teaching. The name "Jupyter" comes from the three first languages IPython notebooks supported via "kernels", Julia, Python, and R. It also supports [many other languages](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages).

I'd be happy to put together a ~1 hour [Work Along](https://mozillascience.github.io/studyGroupHandbook/event-types.html#workalong) formatted demo of Jupyter. I'm sure I can scrape together a lesson for this week as long as it makes sense to start advertising for it only a few days in advance of an already shortened week.

Off the top of my head, topics to live demo:
1. 5 minute what, where, why, who Jupyter notebooks, with examples like:
   - my own work: [teaching geospatial analysis in Python](https://github.com/ceholden/open-geo-tutorial/tree/master/Python/chapters) and [Landsat data preprocessing](https://github.com/ceholden/landsat_preprocess/tree/master/chapters)
   - Jake Vanderplas' awesome [PyCon 2015 machine learning talk](https://github.com/jakevdp/sklearn_pycon2015) or a [reproduction and analysis of a paper on _The Hipster Effect_](https://github.com/jakevdp/jakevdp.github.io/blob/master/downloads/notebooks/HipsterEffect.ipynb)
2. Installation ~ 10 minutes (hopefully)
   - Locally
   - SCC/GEO cluster (also cover how to remote access the notebooks)
3. Basics (25 minutes)
   - Prose -- Markdown
   - Media -- linking in images, videos, etc.
   - Equations -- Latex
   - Languages -- example using Python and R
     - See examples at: https://try.jupyter.org/
4. Advanced (10 minutes)
   - Interactivity with [IPython widgets](https://github.com/ipython/ipywidgets)
5. Sharing (5 minutes)

**Comment by tomhohenstein** [comment]
@ceholden great! I really enjoy using Jupyter and I think it will help others lead sessions. I like your initial outline and I think it offers a lot of opportunity for "hands on" work.  How does next week Wednesday  (10/21) or Thursday (10/22) sound?

**Comment by ceholden** [comment]
@tomhohenstein Great! Thursday (10/22) is a better fit for my schedule.

I asked around a few offices here in my department (E&E) and were thinking that 5-6pm would make for a good time. We have a journal discussion group at 4pm that day so we can probably get a pretty good amount of people to come to the Jupyter notebook demonstration. The same thing happened the first day we met at the BU pub and we were able to snag a lot of people for the intro meeting. I'm welcome to any other suggestions for the timing.

As for the location, I'll try to reserve some space in our department classrooms unless anyone has a better venue.

**Comment by mcrovella** [comment]
Hi - Another good use of Jupyter is for teaching.  We've been using it in CS for teaching linear algebra.  It allows one to interact with the interpreter in class to demonstrate concepts and visualize things like linear systems interactively.    I use the RISE ("live reveal") package which is really a nice way to create lecture slides from a Jupyter notebook.   My lectures are at https://github.com/mcrovella/CS132-Geometric-Algorithms.  Students like downloading the notebooks and experimenting with the code.

**Comment by tomhohenstein** [comment]
@ceholden I'll draft and post an announcement for 10/22 from 5-6. If you're happy using space in your department, I am all for it (just pass along the room location when you have it). 

@mcrovella Great use of Jupyter! I downloaded your repo and opened a few presentations as slides - very cool. Do you think this functionality is best shared as a separate session or could we add it to the 10/22 lesson?

**Comment by ceholden** [comment]
@mcrovella Thanks for sharing your course material. It is truly a great time to be a student or educator with this technology readily available. I'm very happy that @damianavila has advanced the capabilities of Jupyter/IPython to serve as a slide-show via integration with the already great [reveal.js](https://github.com/hakimel/reveal.js/). I meant it implicitly, but it merits mentioning it explicitly: I would be ecstatic to include or collaborate with anyone wanting to introduce and educate our group with respect to the capabilities of Jupyter notebooks. At the very least, I'd love to include the reveal.js functionality you've been using in the "advanced topics" section I had planned. If anyone would like to take up this lesson, I'd be more than happy to defer to a more experienced individual or at least collaborate.

With regard to the physical location, I'll ask our department for a space and get back to everyone with a room number and time. I'll ask for a room with a decent (no 800x600 or similar) projector with enough seating.

**Comment by ceholden** [comment]
I just reserved room 442 (our student lounge) and projector with the Earth & Environment department for Thursday, October 22.

I've forked this repo and will begin in the next few days putting together a Markdown document with installation instructions and a set of Jupyter notebooks for the various demonstrations under the `lessons` folder. Anyone who wants to contribute is more than welcome to.

**Comment by tomhohenstein** [comment]
@ceholden great - if you need any help or run into any issues - reach out and we'll be glad to help

**Comment by tomhohenstein** [comment]
Hi Everyone, 

A quick reminder we will be meeting today from 5:00-6:00 in STO 442. 

Hope to see you there!

**Comment by tomhohenstein** [comment]
Hi Everyone, 

We had a great session last night on Jupyter by @ceholden with 6 attendees. Hopefully, we will add the lesson to the repo soon. 

Best, 

Tom

**Comment by tomhohenstein** [comment]
I should have closed this a month ago : (

**Comment by mcrovella** [comment]
Hey very sorry but it seems I somehow missed the rest of this conversation.   If anyone is interested I'm happy to demo the presentation capabilities of live reveal any time.  Sorry to have missed the meeting.

**Comment by tomhohenstein** [comment]
would you be interested in leading a session on jupyter notebooks the week of Feb 1? We have normally been meeting Thursday evenings around 5:30

**Comment by mcrovella** [comment]
Sure.
