### ISSUE TITLE
A few naive bioinformatics questions for anyone with any experience in sequence analysis

### ISSUE THREAD

**Issue by legolagon** [bulib/studyGroup#15]
Hi,
Any help is greatly appreciated
I had a few very simple and naive questions. ( I am a physics student with no biology background about to handle some serious RNA sequence data).

I am about to get some viral RNA sequence data to analyze and I was wondering if viral RNA sequence data could be analyzed the same way as RNA sequence data of transcriptomes are analyzed. I found a protocol online : http://www.nature.com/nprot/journal/v8/n9/abs/nprot.2013.099.html which does differential expression analysis on RNA sequences.

I have to specify data formats to my collaborator this weekend and I am really at sea because I am not sure I can use Bioconductor and this protocol for what I need.\

Thank you
Ashish

**Comment by tomhohenstein** [comment]
@legolagon - whew, great questions. Are you comfortable using R? Both [DESeq](https://bioconductor.org/packages/release/bioc/html/DESeq.html) and [edgeR](http://bioconductor.org/packages/release/bioc/html/edgeR.html), mentioned in the protocol you posted, are in R. 

Not sure if you can analyze RNA and viral RNA sequence data the same way. You could search [Web of Science](http://webofknowledge.com.ezproxy.bu.edu/WOS) for background literature.

**Comment by legolagon** [comment]
Thanks Tom,
I am learning R currently for this very purpose.  I found out a little about DESeq and edgeR, but what I don't know is if they can be used for viral RNA sequence analysis too which really prompted my question here.

**Comment by tomhohenstein** [comment]
Hi Ashish, 

So I can't speak to the RNA / viral RNA question but it might have been asked at the [Bioconductor support page](https://support.bioconductor.org/) or the libraries' documentation might mention something. Wish I could be more helpful.

**Comment by tomhohenstein** [comment]
@legolagon Hi Ashish, were you able to resolve your question? Curious to hear how it worked out.

**Comment by legolagon** [comment]
well, a little bit. I talked to my advisor and someone who knows a little
bit about the field. We kinda came to some kind of consensus i guess

**Comment by tomhohenstein** [comment]
@legolagon I'm closing this issue for now. Feel free to reopen it if need be.
