### ISSUE TITLE
GitHub Pages for websites 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#16]
Hi Everyone, 

At the end of last night's session we brainstormed some ideas for future sessions. One idea was a session on using GitHub pages for building a websites.  I've setup a few websites using GitHub Pages and am happy to put together a lesson. 

Thoughts? Reactions? 

-Tom

**Comment by ashiklom** [comment]
+1! I've wanted to start a tech-y blog/public lab notebook-type thing using GitHub pages for a while now, but I've never quite had the time to properly tackle Jekyll's learning curve.

**Comment by tomhohenstein** [comment]
What do you think? Should we schedule a session for the week of Nov. 16?

**Comment by ashiklom** [comment]
That sounds good!

**Comment by tomhohenstein** [comment]
How does Nov. 19 sound? We can do our normal Thursday time.

**Comment by parevalo** [comment]
Sounds good to me.

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Thank you to everyone who attended. We had 9 participants.
