### ISSUE TITLE
Kaggle Competition 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#17]
Hi Everyone, 

We had a small but great Kaggle-focused coworking session on Nov. 5. I believe there is enough interest that we can schedule a number of coworking session that focus on the [Kaggle Competitions](https://www.kaggle.com/competitions). 

If you're interested in learning more about Kaggle Competitions or just learning more about data science, join us for these coworking session. 

The next session will be **Monday, November 9 from 5-7 in STO 442**. 

Best, 

Tom

**Comment by legolagon** [comment]
I will be there at 6 actually, and not 5 as I said earlier  because I have
an advisor meeting that was just scheduled.

**Comment by tomhohenstein** [comment]
No worries - we will see you then! 

-Tom

**Comment by tonygardella** [comment]
I'll be there late as well. Probably around 5:30 pm.

**Comment by tomhohenstein** [comment]
I'm closing this for the new semester, however, we can continue this during the spring
