### ISSUE TITLE
Lighting Talks - Dec. 3

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#18]
Hi Everyone, 

One of the session types that Mozilla recommends is a "[Coding Lighting Demo](http://mozillascience.github.io/studyGroupHandbook/event-types.html)" a.k.a. Lighting Talks. These sessions are designed to give us a chance to showcase our work - no matter how big or small - and practice our presentation skills in a relaxed atmosphere. It is also worth noting that the presentations are normally only 5-8 minutes. 

With the end of the semester nearing, we thought a Lighting Talk session would be a great chance test run conference materials or final presentations. 

If you're interested in presenting, simply add a comment with a one sentence blurb and we will add you to the agenda. The tentative time for this session is Dec. 3 from 5-6:30 in STO 442 (but I'm going to investigate another location). 

Best, 

Tom

**Comment by ceholden** [comment]
I'd be happy to start off by demoing a project I've worked on for, _gasp_, 2.5 years now -- [TSTools](https://github.com/ceholden/TSTools). 

[TSTools](https://github.com/ceholden/TSTools) is a plugin for QGIS written in Python that helps remote sensing scientists visualize the spatial and temporal dimensions of spatial timeseries data by quickly linking image representations in a full GIS with interactive graphs.

**Comment by tomhohenstein** [comment]
whoa - very cool. I'm also happy to give a quick talk about a python library for Google Analytics that I have been using called, simply enough, [Google Analytics for Python](https://github.com/debrouwere/google-analytics)

**Comment by ceholden** [comment]
That sounds great as well. I'm very interested in getting more exposure to that, especially if you had any examples of monitoring traffic with those sorts of tools.

**Comment by keithfma** [comment]
I can give a quick demo. I'm not sure which project I want to show, it will be either:
- A Particle Image Velocimetry ([PIV](https://en.wikipedia.org/wiki/Particle_image_velocimetry)) program I wrote to measure velocity from images of an analog model mountain belt made of sand.
  
  ...or...
- An image analysis program I wrote to estimate the spatial distribution of bone in the femurs of human ancestors.

**Comment by ceholden** [comment]
Both sound awesome, @keithfma. My selfish vote would be for the PIV program as it parallels so closely to some really interesting work I've seen tracking glaciers or icebergs using satellite data, just at a much higher frequency.

**Comment by tomhohenstein** [comment]
@keithfma maybe we will have time for both : ) 

Anyone have a preference for the order tonight? We could go from "easy" to "hard" (i.e. @tomhohenstein, @ceholden, @keithfma) 

Also, is @ashiklom hoping to present too?

**Comment by ashiklom** [comment]
Sure! I'll show off a bit of my R radiative transfer modeling package, and (for those interested) can talk about bits of R optimization that I've discovered in the process as well as how to get Fortran code to play nicely with R.

**Comment by ashiklom** [comment]
Any chance we can start this closer to 5:30? My class that was originally scheduled 12:30-2:00 got moved to 4:00-5:30 (though hopefully we'll get out a little early).

**Comment by tomhohenstein** [comment]
Let's do a "lazy" start to try to accommodate everyone as best as possible.

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Great session - I really enjoyed hearing about everyone's work. I'm closing this one. 

Attendance: 8
