### ISSUE TITLE
1/21 - Hacky Hour - BU Pub - 6-7 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#23]
Hi Everyone, 

We have reserved space at BU Pub for 6-7 on Thursday, 1/21. We will talk about the upcoming events for the semester (possibly adding more) and do some general introductions. 

If you think you'll make it, add a comment to the issue (that will help us track attendance). 

Best, 

Tom

**Comment by ceholden** [comment]
Sounds good!

**Comment by duanyutong** [comment]
Going.

**Comment by parevalo** [comment]
I'll be there

**Comment by tpudlik** [comment]
I'm coming!

**Comment by kswiley** [comment]
I'll be there

**Comment by sassymassey11** [comment]
See you there!

**Comment by tonygardella** [comment]
I'll be there

**Comment by opth13** [comment]
I'll be there

**Comment by tomhohenstein** [comment]
Closing this issue. We had roughly 10 participants : )
