### ISSUE TITLE
1/28 - Introduction to GitHub - STO 442

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#24]
Hi Everyone, 

We thought the best way to start the semester would with a quick introduction to GitHub (and a little Git). 

We are scheduled for 442 and @ashiklom is taking the lead!

**Comment by bderoo-BU** [comment]
Is this happening on 1/27 or 1/28?  The main page still lists the 28th.

**Comment by tomhohenstein** [comment]
1/28 - Thursday!

**Comment by katgit** [comment]
Hey Tom, I could not find the time for this and the following events. Is the time already set or you are going to discuss it at the Pub event?
--Katia Oleinik, RCS

**Comment by tomhohenstein** [comment]
@katgit - the schedule is always fluid : ) We can always add follow up events and we are hoping to talk about the schedule on Thursday.

**Comment by jlems** [comment]
What time does the git workshop run till?

**Comment by bderoo-BU** [comment]
It'll run at least until 7:00, but we may stay and go over if people are interested

**Comment by jlems** [comment]
Thanks!

Could you give a quick summary of what kind of Github concepts you will be
going over?

Thanks once again.

On Tue, Jan 26, 2016 at 12:30 PM, bderoo-BU notifications@github.com
wrote:

> It'll run at least until 7:00, but we may stay and go over if people are
> interested
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bulib/studyGroup/issues/24#issuecomment-175131131.

## 

Jose Lemus

**Comment by ashiklom** [comment]
We'll probably spend the first half on basic command line Git concepts without touching GitHub, so fundamentals of version control, committing code, viewing past changes, reverting commits, and, time permitting, more advanced stuff like branching and merging.

For the second half, we'll cover the basics of working with remote remote repositories (specifically GitHub), including pushing and pulling your own repositories as well as working collaboratively through forking and pull requests.

We'll try to keep the schedule pretty loose to allow time for people to ask project-specific questions (e.g. "I want to do X with my project. How do I do that with Git(Hub)?") and to troubleshoot Git installation problems, etc.

**Comment by ceholden** [comment]
Resources referenced tonight:
- [codecademy: Learn Git](https://www.codecademy.com/learn/learn-git)
- [Github Octocat tutorial](https://try.github.io)
- [Software Carpentry: Version Control with Git](https://swcarpentry.github.io/git-novice/)
  - Now published as a paper in [PLOS Computational Biology](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668)!
- [Software Carpentry tutorial at SciPy 2015](https://www.youtube.com/watch?v=hKFNPxxkbO0)
- [Git Book](https://git-scm.com/book/en/v2)
  - [Git cheat-sheet](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf)

**Comment by tomhohenstein** [comment]
12 attendees. 

Lesson learned - improve communication about time of event.
