### ISSUE TITLE
2/4 - Using Jupyter - 5:00-6:00 - STO 442

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#25]
Hi Everyone, 

This session will be on using [Jupyter Notebooks](http://jupyter.org/). Feel free to add any comments or suggestions to this issue.

**Comment by ceholden** [comment]
I'd be happy to lead this demonstration again, but I think @mcrovella would be best suited as he uses Jupyter notebooks with the slide show extension for teaching university classes (see #14). I'm really curious to hear his experience and get some tips and tricks.

Mark me down as interested and as backup lead.

**Comment by mcrovella** [comment]
I am happy to demonstrate the use of Jupyter notebooks for making presentations and teaching.   (Maybe the title should reflect that.)    

Should I plan on doing this on 2/4?   (What is the time and location?).

**Comment by tomhohenstein** [comment]
We have normally been having sessions start around 5 or 5:30. STO 442 has been a default location but we can certainly change it up

**Comment by mcrovella** [comment]
OK, I will plan on STO 442 at 5pm -- let me know (by email) if that changes, otherwise, see you then.

**Comment by ceholden** [comment]
"Talk Python To Me" podcast about Jupyter project: [Episode #44: Project Jupyter and IPython](https://talkpython.fm/episodes/show/44/project-jupyter-and-ipython)

Highlights:

> One of the fastest growing areas in Python is scientific computing. In scientific computing with Python, there are a few key packages that make it special. These include NumPy / SciPy / and related packages. The one that brings it all together, visually, is IPython (now known as Project Jupyter). That's the topic on episode 44 of Talk Python To Me. 
> 
> You'll learn about "the big split", the plans for the recent $6 million in funding, Jupyter at CERN and the LHC and more with Min RK & Matthias Bussonnier. 

I highly recommend listening if you're curious about the project and have 1 hour to spare.

**Comment by ceholden** [comment]
Links from tonight:
- [RISE - Reveal Jupyter/IPython Slideshow Extension](https://github.com/damianavila/RISE)
- [IRkernel - R kernel for Jupyter notebooks](https://github.com/IRkernel/IRkernel)

**Comment by tomhohenstein** [comment]
Looks like it was a great event - thank you for posting the links. 

Quick question - about how many people made it?

**Comment by mcrovella** [comment]
I think about 6-7, myself included.

**Comment by tomhohenstein** [comment]
Great work - @mcrovella I hope you enjoyed presenting. I heard you got into using RISE :+1:
