### ISSUE TITLE
2/11 - Git Advanced - 5:00-7:00 - STO 442 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#26]
Looking to learn more about Git? This session is for you. You'll want some familiarity with Git and GitHub to get the most out of this session but everyone is welcome to attend.

**Comment by ashiklom** [comment]
5pm to 7pm, in STO 442.

**Comment by ashiklom** [comment]
One suggested topic is submodules.

**Comment by tomhohenstein** [comment]
@ashiklom sounds great!

**Comment by ceholden** [comment]
Just FYI I reserved the room for the time listed already with Fred.

**Comment by ceholden** [comment]
**UPDATE**: our reservation has been shifted to the nearby room 435 (ROTC and E&E department computing lab).

I'll try to redirect people, but FYI

**Comment by ceholden** [comment]
Thanks to Alexey for leading this event. We had 5 people attend and covered the following about Git:
- `git rebase`
  - how to rewrite history to fix mistakes, reword useless commit messages, merge commits together, etc.
- `git filter-branch`
  - demonstrated how to remove sensitive or large files from history
- `git submodule`
  - how to add submodules
  - how to update submodules used within a repo
  - why it might be a good or bad idea to use submodules
- `git log --follow <file>`
  - track a file through version history

**Comment by tomhohenstein** [comment]
great work!
