### ISSUE TITLE
2/18 - Vagrant - 5:00-7:00 - STO 442

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#27]
[Vagrant](https://www.vagrantup.com/) allows you to create and share reproducible development environments. This is a great solution for those "well, it works on my machine" problems. 

For more ideas and suggestions, please comment on this post. 

-Tom

**Comment by ceholden** [comment]
I would be happy to lead this session or share my experience using Vagrant to deploy some scientific software. 

As an example resource, the [Data Science Toolbox](https://github.com/DataScienceToolbox/data-science-toolbox) ([Github](https://github.com/DataScienceToolbox/data-science-toolbox)) uses Vagrant to make getting an environment up and running simple.

Paging @bcow: this might be of interest to you or the others on the PEcAn project as it replicates the end result of distributing a VM image without the complications of versioning and hosting a 4GB blob.

**Comment by tomhohenstein** [comment]
Still a few weeks out but what are we thinking for time and location?

**Comment by ceholden** [comment]
I've just reserved with Fred (E&E dept admin) the STO 442 student lounge from 5-7pm.

So:
- Location: STO 442 (Earth & Environment student lounge)
- Time: 5-7pm

**Comment by tomhohenstein** [comment]
great! I updated the issue, calendar, and website. I'm looking forward to this session.

**Comment by ceholden** [comment]
It's still a week away, but if anyone is looking to attend and follow along with the demonstration they'll need a few pieces of software that would be good to have installed beforehand. The two dependencies are free, open-source, and cross platform so you can use them on Mac/Windows/Linux without issue.
1. [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
   - We'll be using VirtualBox to host our virtual machines "provisioned", or setup, by Vagrant
2. [Vagrant](https://www.vagrantup.com/) 
   - Vagrant is used to setup virtual machines

If you're a Windows user, you're going to also need a SSH client such as [Putty](http://www.putty.org/) or [MobaXTerm](http://mobaxterm.mobatek.net/). Mac and Linux users have terminals as a standard part of the OS so they can skip this step.

Unless someone else has a suggestion, I was going to demonstrate Vagrant using the [Data Science Toolbox](http://datasciencetoolbox.org/). There's a very nice instruction guide for how they use Vagrant to get a Jupyter Notebook session running within the "Data Science Toolbox" environment. I can also demo how I use Vagrant in my own work to distribute some software I wrote.

**Comment by ceholden** [comment]
Hi everyone

Just a reminder -- we'll be meeting tonight at 5pm in STO442 to discuss the Vagrant technology for creating reproducible environments for scientific usage.

I'll live-demo how to setup the [Data Science Toolbox](http://datasciencetoolbox.org/) by following along the guide for hosting Jupyter notebooks.

I'll also cover the following examples from my own work:
- [Vagrant to setup QGIS and other dependencies for TSTools](https://github.com/ceholden/TSTools)
- [Vagrant to compile and configure Landsat preprocessing software from USGS](https://github.com/ceholden/espa-vagrant)

**Comment by ashiklom** [comment]
Note for Windows users: When you install Vagrant, you also need to add it to your `PATH` variable in MobaXterm (not sure about Putty).

To do this, from MobaXterm, run the following command:

```
echo 'export PATH=$PATH:/drives/c/<path to vagrant executable>'
```

Note that you will have to escape parentheses and spaces with backslashes (`\`). For instance, my path looks like:

```
/drives/c/Program\ Files\ \(x86\)/Vagrant/bin
```

You'll then need to either restart MobaXterm, or run `source .bashrc`.

To check that the path is loaded, you can run:

```
echo $PATH
```

**Comment by parevalo** [comment]
Actually, you can just got to mobaxterm configuration, click on the
"terminal" tab and set "use windows path environment".

**Comment by ceholden** [comment]
Thanks for coming last night. I think we had 7 people in attendance (including me) for the demo and discussion of Vagrant. We might have even secured a leader for a future discussion on Docker!

**Comment by tomhohenstein** [comment]
@ceholden nice work - let's talk about documenting the lesson. I'm happy to help write it up (it doesn't have to be long to be good)
