### ISSUE TITLE
Welcome! And Read Me

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#3]
Greetings, 

Thank you for visiting BU's Study Group. This group is designed to bring everyone in the BU community interested in improving their code, enhancing their data analysis abilities, building new skills, and working in a collaborative environment together. We are a community-led group that's open to new ideas and here to work with you. 

We are using Github's issue tracker to suggest events and to post discussion items. It is a little bit of a workaround but the functionality is great (and the cost is free : ). 

Please add a comment to say hello. If you're interested in learning a new technology or sharing something you know, create a new issue. 

Best, 

Tom

**Comment by ashiklom** [comment]
Would something like this be better off as the README file in the main repo? Perhaps we could work together on updating the current README, which seems to just be a generic one from Mozilla's StudyGroup project.

**Comment by tomhohenstein** [comment]
@ashiklom Excellent idea! Let's work on that. (And you're right it is a the standard Mozilla template). 

I did a quick update on the Readme.md file. I also created a team for the study group that will - if I have done this correctly - let members edit and update the repo (I also added you to the team).

**Comment by tomhohenstein** [comment]
I'm going to close this issue. We have a new README.md file to introduce our repo and can continue to edit and refine it as need.
