### ISSUE TITLE
4/7 - Coworking Session - 5:00-7:00 - STO 442

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#31]
Come join us for a coworking session. These are great sessions to work on your project and reinforce the lessons we have already learned.

**Comment by tomhohenstein** [comment]
Changing this to 4/7 so we can do R Shiny on 3/24

**Comment by tomhohenstein** [comment]
One idea is to do a code review session following [Mozilla's guide](http://mozillascience.github.io/codeReview/design.html). 

Thoughts?

**Comment by ashiklom** [comment]
I think code review would be a fantastic idea. We've started doing it internally in our lab, and it's been great. Having some outside opinion would be even better.

:+1:

**Comment by tomhohenstein** [comment]
One idea I heard in a Study Group call was having 10-15 minute code reviews that the group would look at. Thoughts? Ideas?

**Comment by ashiklom** [comment]
:+1: That sounds great! Is it something we'd do at every study group meeting, or something that we'd schedule independently?

Alternatively, we could set up a system of rotating code/repository review, where somebody volunteers their script/repository each week and the rest of us comment on it. That way, we don't have to worry about scheduling conflicts. We could do this just through vanilla GitHub, but maybe there's some nice open-source code review software that we could leverage? From 2 minutes of Googling, I found [Gerrit](https://www.gerritcodereview.com/), which could be promising, though I haven't tested it.

**Comment by tomhohenstein** [comment]
@ceholden  @wkearn  - thoughts? Suggestions? It could also be interesting to try to connect with a few CS folks.

**Comment by ceholden** [comment]
:+1: for me on code review. We've taken baby steps toward implementing this in our lab group, but we're basically flying blind on what to do and what strategies to employ. I'd love to see what others are doing or just chat about code review, especially if we could get some CS people to come hangout.

I haven't used any software dedicated to code review (like Gerrit that Alexey mentioned), but I have some understanding of how to do a code review using Github by following a handful of open source projects that basically do code review during a PR. These projects are small enough or have small enough needs for Github's built-in tools to accommodate, but I suspect it would break down at scale where a dedicated software would really shine.

**Comment by ashiklom** [comment]
Code review via Pull Requests is exactly how we do it in our lab, and it
works pretty well, but as you mentioned, those are typically pretty small
changes. Also, I think the kind of code review we'd do here wouldn't
necessarily lend itself to that format, unless we create new repositories
and submit toy pull requests to them, which feels kind of awkward.

## :+1: for getting CS people involved.

**Comment by tomhohenstein** [comment]
If there is interest tonight perhaps we can talk a little about the summer / #34 as well as do a quick feedback session.

**Comment by tomhohenstein** [comment]
A quick note from today's session, for those interested in Open Refine, the library has a copy of [Using Open Refine](http://buprimo.hosted.exlibrisgroup.com/BU:default_scope:ALMA_BOSU151777442170001161)

**Comment by ashiklom** [comment]
@tomhohenstein Great tip! I look forward to playing with it.

When poking around for possible R packages for interacting with Open Refine, I came across the [IBM Data Scientist Workbench](http://www.r-bloggers.com/ibm-datascientistworkbench-openrefine-rstudio-jupyter-notebooks-in-the-cloud-via-your-browser/), a web interface that combines Open Refine, Rstudio, Jupyter, and some other stuff for facilitating data workflows. Haven't played with it yet, but looks promising!

**Comment by tomhohenstein** [comment]
Very cool - I signed up for it. I'll let you know how it goes. 

Also - last night we had 4 attendees

**Comment by tomhohenstein** [comment]
@keithfma - if we could build a workbench using the cluster, we'd be heros (or nerds) or both. the IBM workbench is pretty pretty cool.
