### ISSUE TITLE
2/10: MATLAB Community Office Hours - MCS 148 - 5:00-6:00

### ISSUE THREAD

**Issue by keithfma** [bulib/studyGroup#32]
We are planning an informal “office hours” session for MATLAB programming on Wednesday 2/10 at 5:00-6:00 PM, at MCS 148.

This session is an opportunity for the BU MATLAB programming community to come together to discuss, and hopefully resolve, programming issues we have encountered in our work. All levels of MATLAB experience from any academic area are welcome, and no issue is too small or too big. I (Keith Ma) will lead a group discussion of one issue at a time, and have a projector and laptop for hands-on programming. You can join in with us, or if you prefer, work together in small groups.

**Comment by tomhohenstein** [comment]
+1

**Comment by keithfma** [comment]
I had to shorten the session due to a room scheduling conflict - it will now run for one hour 5:00-6:00 PM.

**Comment by keithfma** [comment]
Due to the snow today, I am rescheduling this session to this Wednesday (2/10). The room and time remain the same.

**Comment by tomhohenstein** [comment]
We'll need to work on our planning for this session.

0 participants
