### ISSUE TITLE
Shell commands / advanced CLI tools

### ISSUE THREAD

**Issue by ashiklom** [bulib/studyGroup#34]
I think it would be great to have someone lead a tutorial on common bash commands, as well as some more advanced tips and tricks for making it easier to work from the command line. I for one would like to learn more about the following topics:
- Redirecting/suppressing output from `stdout/stderr`
- Searching with `find` and `grep`
- Manipulating files with `sed` and `awk`
- CLI text editors (mostly nano, maybe some vi(m), although that could be a whole tutorial by itself)
- Bash (and Perl-based?) regular expressions, and how to use them to intelligently operate on lots of files

**Comment by tomhohenstein** [comment]
I love this idea. I had an dream the other day - summer of bash. Weekly brown bag lunches during the summer that cover one bash command. 

Regular expressions is also a great idea. They are so powerful but I've always struggled with them and rely on Google and Stackoverflow.

**Comment by tomhohenstein** [comment]
Building a list of common bash commands that could be great (15-30 min) topics
- find
- grep
- sed
- awk
- comm 
- diff 
- sort 
- join
- csplit
- split 
- cut 
- jot
- head / tail 
- less / more
- input / outputs 
- tr

**Comment by ceholden** [comment]
The best guide for how to learn these sorts of things I've encountered is the "Unix for Poets" by Kenneth Ward Church way back in AT&T Bell Labs:

https://web.stanford.edu/class/cs124/kwc-unix-for-poets.pdf

The Software Carpentry lesson on Bash is also very good and uses the same basic method of teaching CLI via grep/sed/awking on a text file:
https://swcarpentry.github.io/shell-novice/

**Comment by tomhohenstein** [comment]
added to #44 - closing issue for now.
