### ISSUE TITLE
3/31 - Julia - STO 442 - 5:00-7:00 

### ISSUE THREAD

**Issue by wkearn** [bulib/studyGroup#37]
Alexey and I were chatting the other day, and he said there might be some interest in an intro to Julia. I'd love to drop by one week and show it off. 

I could imagine a tutorial getting people programming in Julia, or I could do more of a demonstration of how Julia's design enables writing very fast code fairly easily. The former might be more useful and easier to follow, but Julia really shines when you're neck-deep in numerical computations, and you need a fairly complex application before you can really see the benefits. Let me know what you all would be interested in.

And now that I've found this repo, I'll start coming to the study group. Looking forward to meeting everyone!

**Comment by ceholden** [comment]
Awesome! I am very excited to learn more about Julia. I've heard much about the JIT magic that makes it fast and that Julia can basically sit on top of the existing scientific Python and C/Fortran ecosystems, but I haven't seen many demonstrations that weren't Fibonacci level of trivial. Personally, I would favor seeing project examples of yours using Julia that get more in depth and, as you say, demonstrate the strengths of the language.

**Comment by tomhohenstein** [comment]
+1 @wkearn - any interest in scheduling a day / time to talk about Julia?

**Comment by wkearn** [comment]
Sure! Looking at #19, it seems like March 31 is free. That works for me.

**Comment by tomhohenstein** [comment]
great! I'll start doing the updates

**Comment by wkearn** [comment]
I've uploaded a little Julia module that we'll be playing around with tomorrow to [wkearn/GeometryRandomFields.jl](https://github.com/wkearn/GeometryRandomFields.jl). There is a Jupyter notebook that we'll be looking at in the `examples` directory.

If you have a Google email account, you can experiment tomorrow with Julia on [JuliaBox](https://www.juliabox.org/). It's a little tricky to get everything properly set up, so I'll go over that tomorrow. If you really want to try it out now, let me know, and I'll help you through it.

If you already have Julia installed locally or [want to install it locally](http://julialang.org/downloads/), you'll need to make sure that you have version 0.4 of Julia (the current release, not the development v0.5). Everything should work with any official release of v0.4, but JuliaBox will be using the most recent v0.4.5.

Once you have Julia installed, fire up what's called the REPL (in a terminal, type `julia`) and enter the following commands to get the packages we'll need to use:

``` julia
> Pkg.add("Plots")
> Pkg.add("GR")
> Pkg.add("IJulia")
```

This adds [`Plots.jl`](https://github.com/tbreloff/Plots.jl) and the [`GR.jl`](https://github.com/jheinen/GR.jl) plotting backend as well as the IJulia kernel which connects Julia to Jupyter notebooks. You can also use `Plots.jl` with `PyPlot.jl` (`Pkg.add("PyPlot")`), though the beauty of `Plots.jl` is that everything should work the same regardless of which plotting backend you use.

You should, at this point, be able to run through the notebook in the `examples` folder of the `GeometryRandomFields.jl` package I linked to without any errors. Let me know if anything goes wrong.

I can open a pull request to add the notebook to the lessons folder, or if we figure out how to use submodules (#21), I can add the `GeometryRandomFields.jl` repo as a submodule. Let me know which is a better option.

**Comment by tomhohenstein** [comment]
@wkearn great work! I'm really looking forward to tomorrow's session.

**Comment by tomhohenstein** [comment]
I counted 7 people - great session

**Comment by mybeliza** [comment]
Hello All,

A friend of mine bought two tix to the Questrom spring formal
tomorrow. Now, she has injured her foot and can't make it. Anybody looking
for spring formal tix? I know they've been sold out for a while now. She's
willing to sell them at $80 instead of $90 for two.

Regards,
Myrdell
