### ISSUE TITLE
4/14 - Off week 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#39]
Creating a placeholder for a potential session on 4/14. 

Two ideas follow [Bill Mill's Awk lesson](https://github.com/BillMills/awk-lesson/tree/2d38587eb3f21bd9dc6cfab9b3157217ac1ee620) or do a session on [Drake](https://github.com/Factual/drake).

**Comment by tomhohenstein** [comment]
At last week's session we talked about doing a session on Make. Any interest in this? If so, is anyone interested in leading?

**Comment by ashiklom** [comment]
:+1: Yes please! If we have time, it would be great for someone to talk about [autoconf](https://en.wikipedia.org/wiki/Autoconf) as well, if anyone feels qualified. I've seen it used a lot in source packages I've installed, and I've always wanted to learn how to use it but never got around to it.

**Comment by tomhohenstein** [comment]
@keithfma @mattbuechler  know anyone that might be interested in an informal overview of make and/or autoconf?

**Comment by mattbuechler** [comment]
I personally would be interested in make and in particular in autoconf.

**Comment by tomhohenstein** [comment]
Quick question - how many people will be attending the software carpentry session on 4/14? I'm curious if we want to hold a session or have an off week.

**Comment by ceholden** [comment]
I will be attending the Software Carpentry session -- I'm probably going to be burnt out or behind in other work and don't think it likely I'll attend study group that week.

**Comment by ashiklom** [comment]
I'll also be at the software carpentry session, and I second @ceholden's
opinion -- it might be nice to have a week off to have extra time to catch
up on coursework, especially as we approach the end of the semester/finals

## week.

**Comment by tomhohenstein** [comment]
sounds perfectly reasonable to me. Let's make this an off week.

**Comment by tomhohenstein** [comment]
zero attendance : )
