### ISSUE TITLE
Hacky Hour - BU Pub - Sept. 17 @ 5:00

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#4]
**Where:** [BU Pub](http://www.bu.edu/dining/where-to-eat/retail-dining/bu-pub/)
**When:** Sept. 15 from 4:00-5:30
**Who:** All are welcome!

Hi Everyone, 

We are going to have our first  Hacky Hour on Sept. 15 from 4:00-5:30 at the BU Pub. This will be a great chance for us to meet each other, talk about our interests, and plan for the upcoming term.

Also, if you're interested in leading a session or have an idea for a session, feel free add a comment to this issue. 

Best, 

Tom

p.s. If you have a laptop - feel free to bring it!

**Comment by wangjilin** [comment]
Hi, I'm a first year graduate student in physics. I love coding but I don't know much about it. Would it be ok for a beginner come to this activity?

**Comment by dlebo** [comment]
I'm in for Sept 17 if there's still room.

**Comment by tomhohenstein** [comment]
@wangjilin Yes - we are actually hoping a number of people similar to you will attend. 

@dlebo - there's still room - I hope to see you there!

**Comment by ashiklom** [comment]
I'm a second year Ph.D. student in Earth and Environment. Our lab lives and breathes R and is actively developing scientific software with a bunch of collaborators from other institutions on GitHub. There is a lot of enthusiasm about gatherings like this from many members of our department, so I'm sure you'll get a lot of support from us!

I'll definitely be attending on Thursday, and I'll try to talk a few others from E&E into coming as well.

**Comment by tomhohenstein** [comment]
@ashiklom sounds great! I look forward to meeting you. The great part of the Mozilla Study Group philosophy is that the group should be community led. So while I'm not too familiar with R - it will be great to have members who are and can teach others.

**Comment by adrianyi** [comment]
I'm from physics department, and I'm interested in learning more data analysis programming and would love to be involved with this group.
I'll be there this Thursday as well.

**Comment by tomhohenstein** [comment]
@adrianyi - great! We look forward to meeting you on Thursday! And don't be afraid to bring some friends : )

**Comment by bcow** [comment]
I'm a PhD student in Earth and Environment (in the same lab as @ashiklom) with a background in math and programming. Really looking forward to getting involved!

**Comment by tomhohenstein** [comment]
@bcow awesome - hope to see you there!

**Comment by tomhohenstein** [comment]
We had a great first hacky hour. Thank you to all of those that attended. We definitely had more people (~19) show up than I had anticipate - which is awesome. 

Next we should schedule our next meeting for a Git/GitHub introduction. We will be creating an issue with a poll to help organize that effort. 

If you have any ideas, please add an issue to the repo. And keep telling your friends.
