### ISSUE TITLE
4/21 - Hacky Hour - BU Pub - 5:00-6:00 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#40]
It would be great to do some assessment of the group and to think about ways to improve group.

**Comment by tomhohenstein** [comment]
Hi Everyone, 

I know many people are focused on wrapping up the semester and preparing for the summer. I thought it might be nice to change this from a coworking session to a hacky hour. 

Thoughts?

**Comment by ashiklom** [comment]
I actually have plans for that evening and won't be able to make it either way.

**Comment by ceholden** [comment]
I'm up for attending it as a hacky hour. I have about a hundred thoughts pinging around my head coming off of the Software Carpentry "teach us how to teach" workshop that I'd love to discuss.

**Comment by tomhohenstein** [comment]
It would be great to hear about the software carpentry session. 

Thoughts on location? We can always hit the BU Pub if need be (but it might be nice to scout a potential spot for the lightning talk session)

**Comment by jebyrnes** [comment]
Chiming in from outside - huzzah to hacky hour. I wonder if a Boston Scientific Computing Hacky Hour might be a good meetup group?

**Comment by tomhohenstein** [comment]
@jebyrnes - interesting idea. Are you thinking about creating a meetup.com kind of thing or doing outreach at specific places?

**Comment by tomhohenstein** [comment]
Any additional thoughts for Thursday? I'd like to send an email with the time and location early tomorrow morning.

**Comment by tomhohenstein** [comment]
Updated the issue and sent an email for a Hacky Hour tomorrow at the BU Pub. @ceholden and @jebyrnes  - hope you can make it!

**Comment by ceholden** [comment]
Great -- looking forward to it. If the weather forecast hasn't changed I
think the patio would be a lovely option at the pub. Rare chance for some
sunshine and we escape the loud music inside.

**Comment by tomhohenstein** [comment]
solid hacky hour session - good conversation and lots of planning.
