### ISSUE TITLE
4/28 - Lightning Talks - STO 442

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#41]
Anyone interested in doing a lightning talk? (@istfer, @wkearn, or @mattbuechler )

**Comment by tomhohenstein** [comment]
Hi Everyone, 

We should start recruiting people for the end of semester lightning talks. Also, maybe we could have this at a local establishment or look at other ways to make the event more social. 

-Tom

**Comment by wkearn** [comment]
I'm up to give a lightning talk! I'll figure out what I can show off and let you know.

**Comment by tomhohenstein** [comment]
great! I'm also open to doing one too but I'd prefer to open the floor up to others (I did one last fall)

**Comment by ceholden** [comment]
Happy to volunteer to demo another project of mine and even happier to be bumped if there's someone who didn't present last semester.

Big :+1: for a "local establishment... more social" which I can only take to mean beer. Does anyone know of a place we could hideaway in at BU and use a projector? I guess we can reserve a section of the Pub and ask that they not blast us with music? The format seems to lend itself to that kind of environment and our biggest turnout was at the BU Pub.

**Comment by ashiklom** [comment]
I have some stuff I could show off. Maybe I'll demonstrate my highly customized Vim setup...

Also :+1: for local establishment / more social. It would also be cool to recruit some folks from other institutions -- @ceholden and I met some lovely folks from UMass Boston and Harvard at the Software Carpentry training, some of whom seemed very enthusiastic about participating in our group.

**Comment by tomhohenstein** [comment]
I think we are going to need to a bit of recruiting to get some more speakers. 

@tonygardella, @adrianyi - any interest in giving a quick talk about some of your work this semester?

**Comment by tonygardella** [comment]
@tomhohenstein Sure! I can put something together to present.

**Comment by tomhohenstein** [comment]
Confirmed speakers thus far @wkearn, @tonygardella, @ceholden (optional) @ashiklom (optional) 

Any interest from @istfer or @valpasq?

**Comment by adrianyi** [comment]
sorry I've been MIA this semester, I had prior engagements on Thursday evenings this semester.
I'll rejoin in summer or fall!

**Comment by istfer** [comment]
@tomhohenstein this looks really interesting, thanks! but my schedule is a little hectic this month, I don't think I will be able to make it

**Comment by tomhohenstein** [comment]
Hope to see everyone tonight!

**Comment by tomhohenstein** [comment]
got the projector

**Comment by tomhohenstein** [comment]
really enjoyed last night's session 

4 in attendance
