### ISSUE TITLE
Summer Planning

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#44]
Hi Everyone! 

Here is a tentative plan for the summer. We are still working on a location for the sessions but here is the quick rundown. 
- Start with some great Software Carpentry inspired sessions on Unix, R, and version control. The goal is to have these be 3-hour sessions followed by a Hacky Hour. Ideally, something like 1-4 in CAS. 
- In June move into Bash / Unix / CLI intermediate or advanced sessions. The current thinking is that these will be brown bag lunch sessions. 
- We'd like to mix in some Hacky Hours to enjoy the sun too 
- August - TBD / Min programming 
## Summer 2016 Plan

| Week of | Date | Session | Trainer or Issue |
| --- | --- | --- | --- |
| May 30 | June 2 | Unix / Bash Software Carpentry Style + Hacky Hour | @wkearn, @ceholden |
| June 6 | June 9 | R Software Carpentry Style + Hacky Hour | @ashiklom, @ceholden |
| June 13 | June 16 | R Software Carpentry Style + Hacky Hour | @ashiklom, @ceholden |
| June 20 | June 23 | Version Control / Git  + Hacky Hour | @wkearn, @bcow |
| June 27 | June 30 (?) | Unix / Bash - redirection | #48 |
| July 4 | July 7 (?) | Unix / Bash - find / grep | #49 |
| July 11 | July 14 (?) | Unix / Bash - regexes | #50 |
| July 18 | July 21 (?) | Unix / Bash -  sed + more regexes | #51 |
| July 25 | July 28 (?) | Unix / Bash - file editing (head, tail, split, csplit, cut, join, comm/diff) | #52 |
| Aug. 1 | Aug 4 (?) | Unix / Bash - awk | #53 |
| Aug. 8 | Aug 11 (?) | Unix / Bash - advanced processes (see below) | #54 |
| Aug. 15 | Aug 18 (?) | Unix / Bash - text editors | #55 |
| Aug. 22 |  | TBD / Off week |  |
| Aug. 29 |  | TBD / Off week |  |

**Comment by tomhohenstein** [comment]
Potential list of Unix / bash lessons  
- Redirecting/suppressing output from stdout/stderr
- Searching with find and grep
- Manipulating files with sed and awk
- CLI text editors (mostly nano, maybe some vi(m), although that could be a whole tutorial by itself)
- Bash (and Perl-based?) regular expressions, and how to use them to intelligently operate on lots of files
- find
- grep
- sed
- awk
- comm
- diff
-  sort
-     join
-     csplit
-     split
-     cut
-     jot
-     head / tail
-     less / more
-     input / outputs
-     tr

**Comment by wkearn** [comment]
Nice list!

I would add cron to the list. And you can't mention vi without emacs : )

We definitely want to think about how to organize them. My suggestion, since we have 8 lunches on the schedule:
1. redirection
2. find/grep
3. regexes
4. sed + more regexes
5. the file editing utilities (head, tail, split, csplit, cut, join, comm/diff)
6. awk
7. advanced processes (xargs, ps, top, kill, cron, named pipes, process substitution, GNU parallel)
8. text editors

**Comment by tomhohenstein** [comment]
great suggestions! I'll set aside time to update the planner tomorrow

**Comment by tomhohenstein** [comment]
I updated the initial issue - now we need to find some trainers and finalize some location details. I'm currently looking into 435/435B for the software carpentry inspired sessions. 

It would be great if we could find an R trainer. Any thoughts or ideas? I'm happy to be a helper if need be.

**Comment by yshen16** [comment]
Hello, everyone!

thank you for inviting me in. I love this study group and would like definitely to participate more, more to learn from you all as well as share more. I can probably add some more contents on Perl and MySql database side stuffs, though I dare not claim that I am an expert. I would love to share with you what I know. 

Yun

**Comment by tomhohenstein** [comment]
@sygwmgit great to hear from you! By any chance you good with regular expressions? We are thinking about some brown bag lunches and the one tentatively scheduled for June 23 could be a good fit (if you like regular expressions)

**Comment by tomhohenstein** [comment]
we have 435 reserved for May 12, 19, 26, and June 2 from 1-4. Once we have the instructors set, I can start the advertising and outreach. 

@keithfma - do you think any of the research computing staff might be interested in either leading sessions or being helpers? The first few sessions are largely from software carpentry and the others will be brown bag lunches

**Comment by tomhohenstein** [comment]
Also, Mozilla has a number of lessons from other study groups at: 

https://github.com/mozillascience/studyGroupLessons

and be sure to [check out the issues too](https://github.com/mozillascience/studyGroupLessons/issues)

**Comment by wkearn** [comment]
I can lead the Bash/Unix software carpentry session and the Version Control/Git if needed. I'm not the best person to lead the R ones, but would be willing to be the helper.

For the Unix/Bash lunches, I'd be up to lead any of them, but awk and the "advanced processes" are the two I'd like to do the most.

I'll bug the people I know around here who might be up to lead the R sessions.

**Comment by tomhohenstein** [comment]
great! I added you to the two unix lunches (awk and advanced processes). I'll help with awk - mostly because I want to learn as much as I can - but we might have to run through the lesson beforehand : ) 

I also might have a helper for the intro unix / bash session on May 12

**Comment by tomhohenstein** [comment]
updated the plan based on our conversations last night 

Still a few things to do: 
- [x] Reserve 132
- [x] Release room 435
- [ ] Define leader / helper roles 
- [x] Find leaders for first 4 sessions 
- [x] Registration form ([demo here](http://goo.gl/forms/pAUwEfY5Ul7QYI9H2)) link: http://goo.gl/forms/Ot0Gci7BvnnJkqKr1
- [x] Add to university calendar ([1](http://www.bu.edu/calendar/))
- [x] Add to bu.edu/research calendar ([2](http://www.bu.edu/research/news-events/calendar-events/))
- [x] Epic email blast 
- [x] Schedule email to list

**Comment by keithfma** [comment]
I would be interested in leading or helping. My schedule is up in the air until the end of the week, so I will have to get back to you all then. 

I will also share this topic with the rest of the RCS staff to see if they are willing and able to join in as well.

**Comment by tomhohenstein** [comment]
sounds great! I'm 100% behind RCS involvement. 

Maybe we could do a planning lunch next week (5/16-5/20) to hammer out some details.

**Comment by tomhohenstein** [comment]
Just an FYI, if we can get 20 people to register for the June workshops I can get the library to provide some snacks / refreshments.

**Comment by ashiklom** [comment]
I tried to put myself down for leading the R tutorials on June 6 and 13 but it didn't work. @tomhohenstein Can you add me to the schedule?

**Comment by tomhohenstein** [comment]
will do!

**Comment by rkstan** [comment]
Hi all, 

Posting here as suggested by Alexey ....

I was wondering if there is any interest/opportunity to run a LaTeX workshop? Just to clarify I would like to learn LaTeX, not teach it. It seems like the summer schedule is already pretty set but maybe in the future? .... Maybe in August 

Thanks, 
Radost

**Comment by angelahe27** [comment]
yes, I'm interested in learning LaTex.

---

Angela Xiaoxue He, PhD
Postdoctoral Associate
Dept. of Speech, Language & Sciences
Boston University
www.angelaxiaoxuehe.com
angelahe.axh@gmail.com
angelahe@bu.edu

**Comment by wkearn** [comment]
I'd be happy to help run a LaTeX workshop if we can find a slot for it.

**Comment by tomhohenstein** [comment]
we could also rework the schedule - happy to add / edit / remove any item. (also, at some point we should breakout the schedule into individual issues)

**Comment by wkearn** [comment]
We got a request for a Blender workshop today.

I learned Blender at a summer camp when I was in high school, but I haven't used it since then. I could probably figure it out.
