### ISSUE TITLE
Upcoming High-Performance Computing training opportunities

### ISSUE THREAD

**Issue by keithfma** [bulib/studyGroup#45]
Hi everyone,

There are two upcoming HPC training events that you might be interested in. The first is an in-person "boot-camp" hosted at BU, and the second is a webinar series. You can find the details at the two links below.

https://portal.xsede.org/course-calendar/-/training-user/class/492/session/985
https://www.olcf.ornl.gov/training-event/webinar-series-best-practices-for-hpc-software-developers/

If you are interested in the Bootcamp, **please register ASAP**. Space is limited and registration is open to the world (including outside BU).

Hope some of you find this useful!

--- Keith

**Comment by tomhohenstein** [comment]
very cool event - I could only make 1st day of the bootcamp. I'm assuming the bootcamp is perfect for first timers? Also, can I add these events to the weekly newsletter?

**Comment by keithfma** [comment]
@tomhohenstein Definitely feel free to share the events around. Amazingly, the Bootcamp has already filled up --- we have 27 registrants for 10 spots. We will probably add a few seats once the room is finalized, but it is still likely to be a full house.

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Looks like the some of the videos have been posted: 
- [Session 1](https://www.youtube.com/watch?v=YJi05p4n1Gc&index=1&list=PL20S5EeApOSuE6BZWEbMMV-9-ZHNAu3NI)
- [Session 2](https://www.youtube.com/watch?v=pnH7JycpfiY&list=PL20S5EeApOSuE6BZWEbMMV-9-ZHNAu3NI&index=2)

The [upcoming sessions](https://www.olcf.ornl.gov/training-event/webinar-series-best-practices-for-hpc-software-developers/) are on June 2, June 15, week of July 14, week of July 28, and the week of August 9.
