### ISSUE TITLE
Open Data Science Conference - Boston May 20-22

### ISSUE THREAD

**Issue by keithfma** [bulib/studyGroup#46]
Some of us may also be interested in this upcoming conference.

[Open Data Science Conference - Boston May 20-22](http://www.odsc.com/boston)

If anyone besides me plans to go, perhaps we can get together for lunch or drinks?

**Comment by ceholden** [comment]
Thanks for the link, Keith! I'm very interested in attending but I have to think on whether the price is worth it versus watching on YouTube (assuming they'll record and upload the talks). Price goes up in 7 days from now so I'll have to decide soon.

Are you going for the 2 or all 3 days?

**Comment by tomhohenstein** [comment]
+1 was hoping to attend but can't make that weekend. should be a great conference

**Comment by keithfma** [comment]
I am registered for the full conference (as training for my job here at BU).

**Comment by ashiklom** [comment]
Alas, I'm out of town that weekend. But I'd be keen on seeing some of the talks on YouTube.

**Comment by wangathan** [comment]
I might be interested if we can figure out maybe the group discount? Needs
5 or more people... I wonder if that stacks with the student discount.

**Comment by tomhohenstein** [comment]
probably worth reaching out to them about a group student discount - seems like we might be able to round up 5 ppl.

**Comment by adrianyi** [comment]
I'm definitely interested and likely to register.
-Adrian

**Comment by ceholden** [comment]
:+1: for trying to register as a group if that'll get the price down a bit. 

I might have to get a new BU ID for them to believe I'm still a student! My photo is from 10 years ago as a freshman!

**Comment by wangathan** [comment]
I've sent an email to the Dept of Earth and Environment to see if there are
any takers there. Let me know if you're interested in joining the group by
Friday morning!

Jon

**Comment by tomhohenstein** [comment]
@wangathan let us know how this goes (and when it is appropriate to close this issue)

**Comment by wangathan** [comment]
It sounds like we've got three "yes" (me, Betsy, Adrian), two "maybe" (Eric
B, Chris? Are you in?), and a post-doc or two. So it seems likely that we
can get the discount... I suspect the size of the discount depends on the
size of our group. The price goes up on Friday so I'm waiting til Friday
morning to make the call there.

**Comment by ceholden** [comment]
I'm in!

**Comment by wangathan** [comment]
The ODSC gave me the following code for the group discount:
" That is fine. Your group may use the code ODSC-BuStu for a 15% discount
on student ticket packages. "

I suspect that it's meant to be available for just the 7 people I said
would be coming, so please don't use it if you didn't indicate you were
coming or else somebody else might get screwed out of it! I told them 7
because the people indicating they were interested were me, Besty, Adrian,
Eric, Chris, Drew, and Afshin (I'll let the others know who aren't involved
in study group). Go ahead and sign up. Student + group discount should put
the price at around $170.

I think it's fine to close this issue now.

Cheers!
Jon

**Comment by ceholden** [comment]
Thanks, Jon!

Registering shortly...

**Comment by adrianyi** [comment]
Thanks Jon, registered! :)

**Comment by bcow** [comment]
Thanks so much Jon!!! I'll register asap :)

**Comment by tomhohenstein** [comment]
@wangathan great work!!

**Comment by bcow** [comment]
Is anyone going to the training sessions? 
ie getting the more expensive student ticket

**Comment by wangathan** [comment]
I bought a ticket that included them because I want the option but can't be
bothered to learn about them and make a decision right now.

**Comment by tomhohenstein** [comment]
anyone interested in sharing back about the conference later this summer? Could be an interesting brown bag lunch

**Comment by tomhohenstein** [comment]
Closing this one out - hope everyone enjoys the conference!
