### ISSUE TITLE
Fall Site Updates

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#47]
### Rebuild Repo
- [x] Clearer landing readme 
- [ ] Welcome statement with audience 
- [ ] contribute.md for how to get involved 
### Documentation
- [ ] Event documentation 
### Clean up
- [ ] Push lessons to Mozilla

**Comment by ceholden** [comment]
Do you want to meet sometime soon, perhaps before the first hacky hour, to clear some of these tasks up? It's close to the Fall Equinox! Don't want to be overdue!

**Comment by tomhohenstein** [comment]
that would be great - how does next week look for you?

**Comment by ceholden** [comment]
I think I'll be in all of next week and only have a meeting longer than 1 hour on Tuesday. Would Monday afternoon work for you?

For myself, I'm mostly hoping to accomplish some of the technical aspects to the updates -- submodules, clearing up some Jekyll stuff, and trying to get up to up to speed with Mozilla to facilitate lesson PRs. You probably know more, but it looks like they've changed how they share lessons to use one repo/lesson and either the traditional PRs adding submodules or issues on the `studyGroupLessons` tracker.

**Comment by tomhohenstein** [comment]
I'd like to know more but we are probably in the same spot! 

How does Monday around noon sound? I'm free until 2:30 - I have an event at 3:00.

**Comment by ceholden** [comment]
Does noon thirty work? I have a meeting at 11 and it sometimes runs a bit over 1 hour

**Comment by tomhohenstein** [comment]
that works for me - we can work in my area or i can travel to you. either is good for me

**Comment by ashiklom** [comment]
If y'all don't object, I might sit in (virtually) on the meeting as well,
if only to pick up some web development tricks.

**Comment by ceholden** [comment]
I'd say come to E&E but almost all of our spaces are likely filled by classes or under construction and if we're to include Alexey remotely I'm hesitant to host in my spacious new cube space.

Library then?

**Comment by tomhohenstein** [comment]
I booked the Estin room from 12-2. I enjoy having @ashiklom on the big screen : )  

see you soon!
