### ISSUE TITLE
Week of July 25 - Unix / Bash - File editing

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#52]
Hi Everyone, 

I'm breaking out the summer session ideas - #44 - into individual sessions for planning purposes. We are still looking for a leader for this session. 

Tentative date was July 28 but we can change that.

**Comment by ashiklom** [comment]
To clarify, this session will be discussing commands such as `head`, `tail`, `split`, `csplit`, `cut`, `join`, `diff`, `cdiff`.
