### ISSUE TITLE
Week of August 15 - Unix / Bash - Text Editors

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#55]
Hi Everyone, 

I'm breaking out the summer session ideas - #44 - into individual sessions for planning purposes. We are still looking for a leader for this session. 

Tentative date was August 18 but we can change that.

**Comment by ashiklom** [comment]
I should be around, and would be happy to talk about vim!

**Comment by tomhohenstein** [comment]
closing this - we should add it to the fall semester idea agenda
