### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#56]
via @rkstan - can we have a session on writing in LaTex? See #44 comment with feedback from @angelahe27 and @wkearn

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Here are the notes from our meeting today about hosting a LaTex workshops. Everything below is still tentative and I have reached out to the Center for Career Development to see if they are interested in joining us. 
- LaTex 
  - Date - 7/21 (or the following week based on CCD availability) 
  - Time - 1:00 
  - Location - STO 442 or 132 
  - create etherpad -> https://public.etherpad-mozilla.org/p/BU-LaTeX
- Session - 2 hours
  - 45 minutes content
    - 15 minutes - article class -> sections, text, tables, figures, 
    - 15 minutes - more article class, bibtex 
    - 15 minutes - look at modern CV -> syntax 
  - 20 - 30 minutes from career counseling 
  - rest work / question time 
- What to add in a CV - Career Counseling (check with them) 
  - reach out to career services to talk about CV 
  - academic focus -> mostly grad students

**Comment by tomhohenstein** [comment]
Hi Everyone, 

This session will be 7/28 in STO 442 (unless we can get 132). Unfortunately, the Center for Career Counseling won't be able to join us.

**Comment by angelahe27** [comment]
so, we don't have a session today?

---

Angela Xiaoxue He, PhD
Postdoctoral Associate
Dept. of Speech, Language & Sciences
Boston University
www.angelaxiaoxuehe.com
angelahe.axh@gmail.com
angelahe@bu.edu

**Comment by tomhohenstein** [comment]
unfortunately not, we were hoping to loop the center for career development in but we didn't hear back from them until yesterday and it was too quick of a turnaround to do the session today. We are planning for next week (and I hope you can make it)

**Comment by angelahe27** [comment]
great! coz i can't make it today:)

---

Angela Xiaoxue He, PhD
Postdoctoral Associate
Dept. of Speech, Language & Sciences
Boston University
www.angelaxiaoxuehe.com
angelahe.axh@gmail.com
angelahe@bu.edu

**Comment by tomhohenstein** [comment]
i guess that works then : ) hope to see you next week!
