### ISSUE TITLE
Introduction to GitHub

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#6]
I heard from a few students that an introduction to GitHub might be a useful tutorial. If you're interested, leave a comment and we can schedule a session. 

Best, 

Tom

**Comment by ashiklom** [comment]
I think this would be a great idea. I've been working on developing a Git tutorial (including online Git interfaces like GitHub at the end!) that targets researchers and, more generally, people that may not immediately see the power and utility of version control. Once that's finished, I'b be happy to add it to this repository, and possibly to help lead such a session.

**Comment by tomhohenstein** [comment]
@ashiklom nice - if you want help, I'm happy to contribute. We'll have to talk about this more on Thursday. Also, feel free to add additional issues for other potential topics.

**Comment by ashiklom** [comment]
Here's a [link](https://github.com/ashiklom/tutorials) to my (tiny) repository, which contains the beginning of my Git tutorial. Feel free to fork it, import it as a subtree (preserves the commit, but more complicated), or whatever. Just let me know where you stick it so I can pull it and keep working on it.

**Comment by tomhohenstein** [comment]
Great! I added a [lesson folder](https://github.com/bulib/studyGroup/tree/gh-pages/lessons) to the repo and a folder for your [Introduction-to-git](https://github.com/bulib/studyGroup/tree/gh-pages/lessons/Introduction-to-Git). I'm not sure if this is the perfect solution but it is a start. 

I believe I added you to the be a member of the "BU Study Group Team" so you **should** be able to work in the repo directly. Let me know if there are any issues and try not to break the website : )

Thank you again for taking on the first lesson!

**Comment by tomhohenstein** [comment]
Hi Everyone, 

If you're interested in attending the git session - please fill out the when2meet at: 
http://www.when2meet.com/?3463656-uDG2a

Best, 

Tom

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Our Introduction to Git session - led by @ashiklom will be on Wednesday, 9/30 at 3:00 in Stone 442. 

Hope to see you there, 

Tom

**Comment by tomhohenstein** [comment]
We had 10 participants and lessons have been [added to our lesson plan folder](https://github.com/bulib/studyGroup/tree/gh-pages/lessons/git).
