### ISSUE TITLE
20160921 - Open Science Lighning Talks 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#60]
Date: Sept. 21, 2016
Time: 6:00-7:30
Location: Estin Room - Mugar Library 3rd Floor (Labeled [Interlibrary loan room on this map](http://study.bu.edu/img/BU_lib_floorplans_mugar_fin5-03.png))
Event: Open Science Lightning Talks
Etherpad: https://public.etherpad-mozilla.org/p/BU-Open-Science-Lightning-Talks (sign in to register) 

This session is designed to be an introduction to a few concepts and tools used in open science to help make research more reproducible. Please join us in our new space in the Mugar Library.

Topic / Tool / Speaker 
Version Control / Git / Betsy
Literate Programming / Jupyter Notebooks / Tom 
Transforming Writing / Pandoc / Will 
Accessing Remote Data / CURL & APIs / Chris 
Command Line / Unix / Alexey 

If you have any additional ideas or suggestions - please comment.

**Comment by ashiklom** [comment]
How long are we thinking each of the lightning talks will be? 10 minutes?

**Comment by tomhohenstein** [comment]
10-15 minutes sounds about right. I have a very short jupyter notebook that i'm going to show to help talk through some of the features

**Comment by tomhohenstein** [comment]
@ashiklom are you still planning on video conferencing in? If so, we should do a quick (5-10 minute) test run just to make sure everything works.

**Comment by ashiklom** [comment]
@tomhohenstein Yes, that's the plan. Let's schedule a time that works for both of us on Gitter.

**Comment by tomhohenstein** [comment]
Great session. 11 ppl attended. I've downloaded the etherpad and added it to the studyGroupLesson repo. Please add your talk to the lesson repo.
