### ISSUE TITLE
20160928 - Pandoc 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#61]
Date: Sept. 28, 2016
Time: 6:00-7:30
Location: Estin Room (3rd floor Mugar Library) 
Event: Pandoc 
Etherpad: https://public.etherpad-mozilla.org/p/BU-Pandoc

Hi Everyone, 

I believe we decided to do a pandoc session after the open science lightning talks. Let me know if that's right. 

I have the Estin Room - 3rd floor, Mugar Library - reserved.

**Comment by wkearn** [comment]
Turns out I have jury duty that day. I imagine I'll be back by 6, but I can't make a guarantee.

**Comment by tomhohenstein** [comment]
on the 28th too?  (I was looking at the wrong week when I posted the issue)

**Comment by wkearn** [comment]
Nope, just on the 5th.

**Comment by tomhohenstein** [comment]
😄

**Comment by wkearn** [comment]
Great! What do we want to see? I imagine we'll learn a little more from the lightning talks on Wednesday, but I'm guessing the main things are

Edited, taking into account Alexey's suggestions:
- A brief intro to Markdown and other markup formats (reST, HTML, LaTeX are the other pandoc input formats that someone is likely to run into in the wild)
- Some basic usage. How do you take a Markdown file and turn it into a LaTeX file, a PDF, a website?
- Metadata
- Workflow. How should you structure a writing project to use pandoc? Makefiles might get a mention here
- Slideshows
- Citations
- Fancier things like tables, inline TeX
- Templates
- Filters

What do you all think? Is it worth it to spend time showing how to make slideshows (citations, nice math, etc.) or should I save that to make sure we get to templates? Templates are a real power user thing, but they do open up a lot of possibilities. Perhaps the workflow is the most useful information? Is it better to spend time on that than on getting details to look nice?

And how should we spend our time? An hour of going through this stuff with half an hour for just fooling around? More fooling around time?

**Comment by tomhohenstein** [comment]
I think the list looks great! We could introduce a few use cases - like slideshows or LaTex - and see what the group is interested in.

**Comment by ashiklom** [comment]
Looks great, though I'd move the "Fancier things", "Filters", and "Templates" to the bottom as optional things to do if you have the time. Making sure people have a solid concept of the basic workflow is probably more important than getting into the advanced features, as long as they have a few leads to follow to look things up on their own.

**Comment by wkearn** [comment]
This is for a pandoc-exclusive session next week, not the lightning talks tomorrow. I'm definitely not going to explain templates in 10 minutes.

**Comment by tomhohenstein** [comment]
Thoughts about an etherpad? I'd be happy to make one (and I kind of like using them so ppl can sign in)

**Comment by wkearn** [comment]
That would be great. Your etherpad skills are far more refined than mine. If you send me the link, I can add it to my lightning talk presentation for this evening.

**Comment by tomhohenstein** [comment]
https://public.etherpad-mozilla.org/p/BU-Pandoc

Something to get us started

**Comment by wkearn** [comment]
Just added some installation instructions to the Etherpad

**Comment by wkearn** [comment]
[The lesson repo](https://github.com/bulib/studyGroupLessons/tree/gh-pages/lessons/pandoc). 

I added it to the Etherpad.

**Comment by tomhohenstein** [comment]
great session. ppl 10. i added the etherpad link and text version to the study group lesson repo.
