### ISSUE TITLE
20161109 - Coworking 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#63]
Hi Everyone, 

The library is organizing some events to go along with [OpenCon](http://www.opencon2016.org/). If the group is okay with it, I'd like to save our time to do something related to OpenCon - event TBD. 

Thoughts?

**Comment by aabn** [comment]
Hi everyone,

I'm the Open Access Specialist in the BU Libraries, and I've been talking with Alexey and Tom about coordinating an open science/data presentation for the Study Group, in partnership with the [OpenCon event](http://www.bu.edu/library/disc/opencon-2016-boston-2/) that will be taking place earlier that day.

Two ideas:
- Presentation/demonstration on RStudio, led by someone from BU Research Computing or someone who works with RStudio and is a skilled user.
- Presentation on Open Science Framework. There is a faculty member, [Carey Morewedge](https://osf.io/sv9xp/), who is active on OSF, and we could reach out to him to see if he could do a demonstration of how he’s using OSF in his research.

Would love to hear any thoughts on these ideas. Thanks!

Anna

**Comment by tomhohenstein** [comment]
we could also try to have some skype in from the COS to talk about the OSF.

**Comment by aabn** [comment]
I contacted Carey Morewedge, but unfortunately he is overcommitted and cannot participate in our event. @tomhohenstein do you have a contact at the COS who might be able to Skype in?

**Comment by tomhohenstein** [comment]
I could reach out April about the OSF to see if she's available but we should also have a plan B. 

@bcow @ashiklom @wkearn @ceholden  do you know anyone that might be interested in leading an intro session on docker? We could follow the lesson at:  

https://github.com/mozillascience/studyGroupLessons/issues/61

**Comment by tomhohenstein** [comment]
Any thoughts about doing a "editor" comparison - emacs, vim, and ...

**Comment by tomhohenstein** [comment]
@ceholden @ashiklom are either of you willing to speak about vim? (or know someone who would?)

**Comment by ashiklom** [comment]
I won't actually be around for the event.

**Comment by ceholden** [comment]
I'm afraid I won't be either -- very bad timing to my Fall semester this year. I'll be relatively available after I get back from a meeting on Nov 17th, just a few weeks before the rest of BU enters "finals mode".

**Comment by tomhohenstein** [comment]
Hi Everyone, 

So I now I won't be able to make this session either (wife + unexpected travel = tom daycare pickup). Anyone interested in doing a coworking session or a remote session (aka google hangout)? We can always take a week break or do a hacky hour too. 

-Tom

**Comment by wkearn** [comment]
I'm always up for a coworking session/hacky hour!

**Comment by tomhohenstein** [comment]
thoughts? happy to help organize

**Comment by tomhohenstein** [comment]
I'd like to update the website / send an draft the email on Monday. If a few ppl are interested in a hacky hour or coworking session - I'm happy to go in that direction.

**Comment by wkearn** [comment]
I'll lead a low-key coworking session in the Estin Room on Wednesday. I know at least @bcow and Julia told me they were willing to come, so we'll have a few people.

**Comment by tomhohenstein** [comment]
great! : )

**Comment by wkearn** [comment]
If you are gone, @tomhohenstein, how should I get into the room?

**Comment by tomhohenstein** [comment]
I'll have that coordinated for you. 

Added to the org-mode list : )
