### ISSUE TITLE
Etherpad Archive

### ISSUE THREAD

**Issue by wkearn** [bulib/studyGroup#65]
I found myself wishing we had an archive for all the Etherpads we've had. I added a page with links to the Github wiki [here](https://github.com/bulib/studyGroup/wiki/Etherpads), but it occurs to me that links may not be the best way to maintain things for a while. Should I add the text of each Etherpad to the wiki? Is there a better way to do this?

**Comment by tomhohenstein** [comment]
very good idea! I have a few of them downloaded as text files. I'll look into adding them. 

i also looked into doing this with the website. I have a working demo at: http://study.bu.edu/lessons/

This might be a little easier b/c it takes advantage of the YAML in the existing posts. 

let me know what you think

**Comment by wkearn** [comment]
That's probably a lot better. Do you know what guarantees we have that our Etherpads will persist? I want to try to avoid link rot with these things.

**Comment by tomhohenstein** [comment]
i don't know if we have any guarantees. I can download them as text and add them to the lessons repo for safe keeping

**Comment by tomhohenstein** [comment]
Okay - I think this is done. I created a new branch called archive in the studyGroupLessons repo. I added a folder listing all the etherpads as well as for storing the text downloads of them. 

Here's the link: https://github.com/bulib/studyGroupLessons/tree/archive/etherpads

**Comment by wkearn** [comment]
Thanks, Tom!
