### ISSUE TITLE
20161019-RESTful APIs

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#67]
Thoughts? I'd really enjoy a session on make files.

**Comment by tomhohenstein** [comment]
@mobiusklein @bcow feel free to add more information as needed

**Comment by tomhohenstein** [comment]
from @mobiusklein 

As I understood it, you wanted to me to talk about how to talk to REST APIs out in the wild. I can do that readily using several resources I use:

GlyTouCan - A database of glycan structures with a generic REST JSON API and a SPARQL Endpoint.

UniProt - Each protein or gene can be accessed with REST, and retrieved in several generic formats including JSON, XML, and RDF, as well as more domain specific flat files. UniProt also has a SPARQL Endpoint.

Entrez - The "Web Service" side of GenBank, the National Center for Biotechnology Information has some REST components and some non-REST components which could be useful for demonstrating why REST is a good thing. They provide data in XML, their own flavor of flat files, JSON, and ASN.1.

I have written clients for the first two, and kind of wrote a half-baked client for the 3rd because I was told I couldn't use BioPython, whose client is better. I do this work in Python, but I can show how parts could be done with cURL and grep or R's analogs.

Format Glossary

XML, short for eXtensible Markup Language
The format of choice for enterprise software and hierarchical data. Can encode many relationships in a variety of ways without any consistency and is considered nearly illegible to human beings. Despite that, it was the gold standard in data exchange on the web during the 80s and 90s. It still is used often today, but JSON has supplanted a large market share.

JSON
JavaScript Object Notation. What the "cool kids" are using these days for data exchange because its easy, quick, and expressive. Serializes complex, arbitrarily nested data structures of key-value pairs (objects), arrays, numbers, and strings, and has one of the most optimized parsers on the planet.

RDF, short for Resource Description Framework
A notion for representing semantic networks in one of many different formats, including XML. Semantic Web technology is roughly 10 years old, but has just started to really see serious use in Life Sciences. It allows you to encode arbitrary first order predicate logic in an expressive fashion. This is a W3C specified format and supports "distributed knowledge bases", meaning that it does not assume that all resources reside in the same system, so all resources must be fully qualified URIs (universal resource indicators, a superset of URL)

SPARQL, recursively SPARQL Protocol and RDF Query Language
A query language (like SQL) for querying Semantic Web networks. Rather than write a million REST services to wrap individual SQL queries on your server, you instead expose a SPARQL Endpoint and allow the user to run arbitrarily complex queries they make for themselves. This is better than just providing an SQL Endpoint since most SQL vendors don't provide a way to prevent destructive operations from being executed, or for protecting certain tables from being accessed. Since all you need to transfer to the server is your query, a SPARQL Endpoint satisfies the definition of a REST API.

ASN.1, short for Abstract Syntax Notation 1
If you've ever used a device with multiple communicating microprocessors made in Germany, chances are those processors are communicating in ASN.1. It has more in common with serialization frameworks like Protobuf and Avro than it does with XML or JSON, and parsers are hard to write or expensive to buy because of the complexity therein.

**Comment by mobiusklein** [comment]
How much does the audience know about SQL, JavaScript, and XML? These are probably things I take for granted that I need to gauge how much to _not_ treat these as good things to make comparisons with.

**Comment by tomhohenstein** [comment]
I also created a etherpad for the session at: 

https://public.etherpad-mozilla.org/p/BU-RESTful-APIs

**Comment by tomhohenstein** [comment]
@bcow and @mobiusklein - how are you feeling about Wednesday?

**Comment by mobiusklein** [comment]
I'm still up for presenting how to use REST APIs. I've put together  a few slides, but after that I'll be switching primarily to demonstrative live-coding.

There will be an interactive step since I'll be showcasing a Swagger document, a tool that helps people test out REST APIs in the browser and shows you the equivalent `curl` command.

Any idea about the audience's familiarity with the topics I mentioned above. If not, I'll try to avoid comparing and contrasting things with them.

**Comment by tomhohenstein** [comment]
not sure about everyone's familiarity, you might have to poll the room and adjust from there.  if there's anything ppl should do before the event (sign up / download anything) you can just  add it to the etherpad.

**Comment by bcow** [comment]
Sounds good - I’ll probably have one or two slides as well and a web demo.
I know SQL pretty well but I would not assume that everyone from Earth &
Environment has SQL experience.

**Comment by tomhohenstein** [comment]
great session!

counting: 8 ppl
