### ISSUE TITLE
Semester End / Spring Planning

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#70]
Hello Everyone, 

I hope you had a great break! I'm testing the waters to see if there is interest in a end-of-semester event and to think about planning for the spring.

**Comment by wkearn** [comment]
I'm up for a little gathering next week, but I (and I know at least @ashiklom and @bcow) are going to AGU the week after that, and I think everyone is probably more than a little busy for the end of the semester.

Perhaps we should focus on the Spring then, and gather here the ideas we've had for events but not had a chance to implement.

I have two questions:

1. Is the format of the events (generally a little presentation plus some working time) we've been having what we want? Do we want more working time, more presentation, something else entirely?
2. How can we get a wider variety of people to show up? We had some interest from bioinformatics early in the semester, and attendance certainly plummeted from all disciplines in the last few weeks, but it would be nice to see some more people.

**Comment by tomhohenstein** [comment]
all great questions - curious if we can get a group together before the break or if we should wait until Jan. I'd prefer to meet sooner but understand the time of the semester we are in.

**Comment by ashiklom** [comment]
I don't think I'll be able to do anything before the New Year -- still lots
to do before an upcoming conference.

My two cents on question 2 above: I think the best way to do this is to try
to recruit ambassadors from other departments. The best way to get people
to attend seems to be guilting them in person, which we obviously can't do
effectively outside our own departments. Plus, that will allow us to cater
events closer to the needs of different departments. Not sure about the
best way to do this though -- maybe just ask attendees from other
departments if they would be willing to take on a more active role?

**Comment by tomhohenstein** [comment]
one thing we could do it to survey everyone on the mailing list about interests and what people would be willing to teach. a few other groups have done that with success.

**Comment by tomhohenstein** [comment]
it might also be best to wait until after the new year ...
