### ISSUE TITLE
20170201 - grep, find, and an intro to regular expressions

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#71]
@ashiklom - any interest in leading a session on grep and regular expressions?

**Comment by tomhohenstein** [comment]
maybe we could add find too

**Comment by ashiklom** [comment]
Sure! The ideal time would be the week of February 21-24 because I'm actually in town, but I could also lead one remotely some other week.

**Comment by tomhohenstein** [comment]
we can do that maybe @wkearn and you can switch (and he could do awk pt. 2) 

I can do a grep / find session and introduce, at a basic level regular expressions.

**Comment by wkearn** [comment]
This is old, so I'm going to close this issue.
