### ISSUE TITLE
20170208 - Coworking and Planning

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#72]
I'm happy to take this one - unless there are interested parties

**Comment by wkearn** [comment]
Here's an Etherpad for tomorrow's session:
https://public.etherpad-mozilla.org/p/BU-Spring2017Brainstorming

I'm filling it out with a hypothetical structure for our planning activity. Let me know what you think.

**Comment by tomhohenstein** [comment]
Looks good! Any idea if we know how many people are interested in attending?
