### ISSUE TITLE
Getting Started with R

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/studyGroup#8]
There was a lot of talk at the Hacky Hour about R. I'm starting this issue to help jump start a potential lesson. Hopefully, someone will get the ball rolling.

**Comment by cguard16** [comment]
I would be interested in an intro session to R! I've used SPSS and STATA, but I've never used R before and I'd love to learn it!

**Comment by ashiklom** [comment]
Half of our department (Earth & Environment) and a bunch of folks in Biology use R. If nobody volunteers, I could lead this tutorial, but it might be nice to get some fresh instructors!

**Comment by tomhohenstein** [comment]
I agree with @ashiklom it would be great if we could find someone willing to step in. I'm happy to help with the lesson development. Mozilla has a [number of lessons in R](https://github.com/mozillascience/studyGroupLessons/labels/R) and even [introduction lessons](https://github.com/mozillascience/studyGroupLessons/issues/15) that we could use.

**Comment by ashiklom** [comment]
Also, BU's Research Computing Services has a [bi-annual series of tutorials](http://www.bu.edu/tech/about/training/classroom/rcs-tutorials/), including several on R.

**Comment by tomhohenstein** [comment]
Excellent point! Those sessions are great. Tagging @keithfma and @katgit from RCS (Research Computing Services). I'd also be happy to help schedule follow up R sessions from the RCS tutorials.

**Comment by katgit** [comment]
@tomhohenstein Hi Tom and all. I will be happy to teach an R tutorial and may be a few followup sessions if there is an interest.

**Comment by cguard16** [comment]
Thanks for sharing! I hadn't heard about the BU sessions below and just signed up for the R series. 

I noticed that Python is full already - wow! Does anyone know if they will be offering more Python classes later on this semester?

**Comment by cguard16** [comment]
Also, many job descriptions I've seen list "statistical analysis or computer programming (for example VBA, SQL, MATLAB, Python)" - I'm not currently familiar with any of these. Are these programs complementary? Generally, if you understand one of these languages, is it pretty easy to pick up the others?

**Comment by katgit** [comment]
@cguard16 Reserach Computing organizes tutorials 3 times a year at the beginning of each semester: fall - September/October; spring- January/February and summer - June
Python, MATLAB and R are normally very popular and fill very quickly, 
If the Python session is filled I would highly recommend you to email to help@scc.bu.edu and ask if you still can attend. In many cases we   invite people to attend but cannot guarantee the sitting (but often some people sign up and do not come). You can also email the instructor - Robert Putnam (putnam@bu.edu) directly. If there is enough interest (and the instructor has time and space) we might be able to run an extra Python session.

**Comment by katgit** [comment]
@cguard16  Statistical Analysis can be performed in many languages. Normally it is done using statistical software: R/SAS/SPSS/STATA, but some languages have some libraries that provide some ( limited ) tools to perform some basic statistical analysis. MALTAB, Mathematica, Python and Perl have many statistical packages. 
SQL is the language that is used to deal with databases and has only limited data analysis tools. 
If you are interested in programming, you should look into Python, MATLAB and/or C.
If you are interested in data analysis - R probably is the best tool, though SAS, MATLAB, Python are often used too. It very much depends on the field you are working in.
--Katia Oleinik, RCS

**Comment by tomhohenstein** [comment]
added into #44 - closing issue
