### ISSUE TITLE
20170405 - Let's Make Some Figures

### ISSUE THREAD

**Issue by wkearn** [bulib/studyGroup#83]
What could we do that would seem appealing here towards the end of the semester? I'm thinking something less along the lines of doing good open, reproducible science, and more about getting stuff done. Less git, more pandoc.

**Comment by tomhohenstein** [comment]
maybe something on fine tuning your code or debugging (both newer topics)

**Comment by wkearn** [comment]
I like the debugging idea, but I'll definitely need to think more about how to teach that if we do it.

I talked to some people this evening about event ideas, and they agreed focusing on productivity over project management was a good thing. One idea might be to take a relatively useful software package and go through it together. ggplot and dplyr came up because I was talking to R people, but pandas could work on the python side. I don't really know much about any of these, but I can do some investigation over the weekend.

I think visualization could also be a good thing to go over. "How to make some presentable figures for your class project in R/Python/whatever." Give a little intro to ggplot and/or matplotlib and then have some working time to make some figures and share and talk about them.

**Comment by wkearn** [comment]
Here's an idea for a visualization lesson: 

- Start with a very quick (~10 minutes) presentation about [this journal article](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833), inspired by [this study group lesson](https://github.com/mozillascience/studyGroupLessons/issues/46)
- Have some time (~30 minutes) to work together on making some figures, or making figures that we already have better
- Finish up with a round of super fast lightning talks (~30 minutes depending on attendance) where people can show and explain the figure that they just made

**Comment by wkearn** [comment]
Let's go for the figure making event: Let's Make Some Figures! This will be easy enough to put together and of general interest.

I'll give the website an update since I've written a little blurb for GWISE about this.

**Comment by tomhohenstein** [comment]
sounds great!

We have the Estin Room from 6:00 - 8:00 - do you imagine a 6:30 start?

**Comment by tomhohenstein** [comment]
Also - if you forward me the blurb I can add it to our newsletter and website

**Comment by wkearn** [comment]
Etherpad: https://public.etherpad-mozilla.org/p/BU-figures20170405
Slides: https://docs.google.com/presentation/d/1haEPxEZKhGmNuW7wHyZBA7b-8CG4kHDPKmQ49JPz3Uw/edit?usp=sharing

**Comment by wkearn** [comment]
8 people. Fairly good turnout, mostly from E&E still. Snacks were a big plus.

I think I'll open up an issue to put the materials on the Mozilla studyGroupLessons repo, because I think this was a fairly successful event, and a good and easy one to replicate.

**Comment by wkearn** [comment]
8 people. Fairly good turnout, mostly from E&E still. Snacks were a big plus.

I think I'll open up an issue to put the materials on the Mozilla studyGroupLessons repo, because I think this was a fairly successful event, and a good and easy one to replicate.

**Comment by tomhohenstein** [comment]
great work! also good to know about the snacks.
