### ISSUE TITLE
20170419 -- Intro to Git and Github

### ISSUE THREAD

**Issue by wkearn** [bulib/studyGroup#88]
Discussed at the Hacky Hour, an intro to git and Github would be much appreciated.

We could split up our Software Carpentry material into two days:

1. 04/19/2017 -- Introduction to git/Github
2. 05/03/2017 -- Intermediate git and Github

@bcow and I are happy to lead the lessons.

**Comment by wkearn** [comment]
Our idea is to give a lightweight but pragmatic git and Github lesson. More "Get up and running with version control" than "Fundamentals of version control." We should emphasize Github a little more than we did with the summer workshops, while still being careful to distinguish git from Github.

We can always redirect the attendees to the more intensive summer workshops for the basics.

A tentative lesson plan

# Lesson 1

1. Make sure everyone is signed up on Github and has a version of git installed. Perhaps we should put some of this in the email. @bcow suggested the Github Desktop, but she knows more about that than I do
2. Have everyone fork some example repository that we make and then clone their forks to their local machines
3. Walk through the change-stage-commit workflow a few times to get people going, go over `git log`, `git status`, etc. Troubleshooting and some fixes (`checkout`, `reset`) if they should arise, but leave them out if they don't.

I think this is a good stopping point. Best not to be overly ambitious.

# Lesson 2

1. Have people push the changes they made in Lesson 1 to their forks on Github
2. Open pull requests to upstream. Talk about merging in the context of these pull requests. 
3. Set up an upstream remote and pull everyone's changes in to your local repository and fork.

**Comment by tomhohenstein** [comment]
looks good - do we need to update the website? I can draft an email blast if this is the plan

**Comment by wkearn** [comment]
Yes, a website update and email draft would be much appreciated.

**Comment by mccabete** [comment]
@tomhohenstein and @wkearn I second the email draft. I can see reach out to  GWISE and see if I can send an event reminder to the GWISE email list.  (Got your email Will :))

**Comment by wkearn** [comment]
Here's a first draft:

**What**: Getting started with git and Github
**When**: Wednesday, April 19, 2017 at 6:30 PM and Wednesday, May 3, 2017 at 6:30 PM
**Where**: The Estin Room, 302, in Mugar Library

How many files of different versions of a manuscript or thesis do you have laying around after getting feedback from your supervisor or co-authors? Have you ever wanted to experiment with your code or your manuscript and need to make a new file so that the original is not touched? Have you ever deleted something and wish you hadn’t? Have you ever forgotten what you were doing on a project? All these problems can be fixed by using version control!

The BU Study Group (http://study.bu.edu) is hosting a pair of workshops on how to get started with version control using git and Github. The first workshop (4/19/17) will be focused on getting you up and running with git and Github. All are welcome: no experience with git is necessary! The second workshop (5/3/17) will focus on incorporating version control into personal and collaborative workflows. If you already feel comfortable with the basics of committing files in git, feel free to skip the first workshop and come just to the second workshop.

**Comment by wkearn** [comment]
I should probably say that I copied the first paragraph from @UofTCoders

**Comment by wkearn** [comment]
So I may have gone a bit overboard preparing for this, but we have an example repo for people to clone and use during the lessons: https://github.com/wkearn/studygroup-git

The `lessons` folder there has the lesson mapped out. Perhaps @bcow can check it out and let me know if there are any things I should add or drop.

**Comment by bcow** [comment]
The only thing I might change is that I would have them fork the repo before cloning. So they can see their own copy. Does that make sense?

**Comment by bcow** [comment]
This looks great to me!

**Comment by wkearn** [comment]
Part 1: 7 people including 2 new people!
